server:
  port: 9001

---
spring:
  profiles: dev
  data:
    mongodb.uri: mongodb://localhost:27017/cars_crud

---
spring:
  profiles: prod
  data:
    mongodb:
      authentication-database: admin
      database: cars_crud
      host: localhost
      password: <password>
      port: 27017
      username: <user>

